[package]
name = "test_tool"
version = "0.1.0"
edition = "2024"

[dependencies]
async-nats = "0.46.0"
clap = { version = "4.5.57", features = ["derive"] }
common = { version = "0.1.0", path = "../common" }
tokio = { version = "1.49.0", features = ["full"] }
