[package]
name = "data_persistor"
version = "0.1.0"
edition = "2024"

[dependencies]
async-nats = "0.46.0"
common = { path = "../common"}
tokio = { version = "1.49.0", features = ["full"] }
tracing = "0.1.44"
futures-util = "0.3.31"
