[package]
name = "shorts_service"
version = "0.1.0"
edition = "2024"

[dependencies]
async-nats = "0.46.0"
common = { version = "0.1.0", path = "../common" }
futures-util = "0.3.31"
tokio = { version = "1.49.0", features = ["full"] }
tracing = "0.1.44"
bytes = "1.11.1"
